site_name: Projet personnel
site_author: Étienne Rivard
theme:
  name: material
  language: fr
  features:
    - content.code.copy
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

plugins:
  - search

extra_css:
  - css/extra.css

extra_javascript:
  - javascript/alltarget.js

extra:
  analytics:
    provider: google
    property: G-FRFYDZB41F

nav:
  - 'Page principale': 'index.md'
  - 'Horaire': 'horaire.md'
  - 'Horaire des rencontres de fin de projet': 'horaire_rencontres.md'
  - 'Projet personnel': 'projet_personnel.md'
  - 'À propos': 'apropos.md'
  - "Techniques de l'informatique": 'https://techinfo.profinfo.ca'

markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - markdown_include.include:
      base_path: code
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

docs_dir: 'wiki'
site_dir: 'www'
use_directory_urls: True
