[project]
site_name = "Projet personnel"
site_url = "https://projetpersonnel.profinfo.ca"
site_dir = "site"
docs_dir = "wiki"

nav = [
  {"Page principale" = "index.md"},
  {"Horaire" = "horaire.md"},
  {"Horaire des rencontres de fin de projet" = "horaire_rencontres.md"},
  {"Projet personnel" = "projet_personnel.md"},
  {"À propos" = "apropos.md"},
  {"Techniques de l'informatique" = "https://techinfo.profinfo.ca"},
  {"Déclaration sur l'utilisation de l'IA" = "declaration-ia.md"}
]

extra_css = ["stylesheets/all.css", "stylesheets/extra.css"]

[project.theme.icon]
logo = "fontawesome/solid/database"

[project.theme]
name = "material"
custom_dir = "overrides"
favicon = "favicon.ico"
language = "fr"
features = [
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.sections",
  "navigation.tabs",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
primary = "teal"
accent = "teal"
toggle.icon = "lucide/sun"
toggle.name = "Passer en mode sombre"

[[project.theme.palette]]
scheme = "slate"
primary = "teal"
accent = "teal"
toggle.icon = "lucide/moon"
toggle.name = "Passer en mode clair"


[project.theme.icon.admonition]
note = "fontawesome/solid/note-sticky"
abstract = "fontawesome/solid/book"
info = "fontawesome/solid/circle-info"
tip = "fontawesome/solid/bullhorn"
success = "fontawesome/solid/check"
question = "fontawesome/solid/circle-question"
warning = "fontawesome/solid/triangle-exclamation"
failure = "fontawesome/solid/bomb"
danger = "fontawesome/solid/skull"
bug = "fontawesome/solid/robot"
example = "fontawesome/solid/flask"
quote = "fontawesome/solid/quote-left"

[project.plugins]
search = {}
